const userTypes = {
  SET_CURRRENT_USER: "SET_CURRRENT_USER",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_ERROR: "SIGN_UP_ERROR",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_ERROR: "RESET_PASSWORD_ERROR",
  RESET_AUTH: "RESET_AUTH",
};

export default userTypes;
